#pragma once

// Public AuraLite::UI surface. Application code can include this instead of
// listing widget headers. Prefer this over reaching into overlay / UIA /
// reactive-detail files (those are not part of the published API).

#include "auralite/canvas.h"

#include "auralite/ui/acc.h"
#include "auralite/ui/anim.h"
#include "auralite/ui/application.h"
#include "auralite/ui/node.h"
#include "auralite/ui/theme.h"
#include "auralite/ui/theme_yaml.h"
#include "auralite/ui/types.h"
#include "auralite/ui/window.h"

#include "auralite/ui/absolute.h"
#include "auralite/ui/column.h"
#include "auralite/ui/row.h"
#include "auralite/ui/scroll_view.h"
#include "auralite/ui/split_view.h"
#include "auralite/ui/tab.h"
#include "auralite/ui/tile.h"

#include "auralite/ui/button.h"
#include "auralite/ui/checkbox.h"
#include "auralite/ui/civil_date.h"
#include "auralite/ui/color_picker.h"
#include "auralite/ui/combo.h"
#include "auralite/ui/context_menu.h"
#include "auralite/ui/data_grid.h"
#include "auralite/ui/date_picker.h"
#include "auralite/ui/image_button.h"
#include "auralite/ui/image_view.h"
#include "auralite/ui/item_list.h"
#include "auralite/ui/label.h"
#include "auralite/ui/list_columns.h"
#include "auralite/ui/list_view.h"
#include "auralite/ui/menu_bar.h"
#include "auralite/ui/menu_item.h"
#include "auralite/ui/native_host.h"
#include "auralite/ui/popup_host.h"
#include "auralite/ui/progress_bar.h"
#include "auralite/ui/radio.h"
#include "auralite/ui/slider.h"
#include "auralite/ui/spin_box.h"
#include "auralite/ui/status_bar.h"
#include "auralite/ui/submenu.h"
#include "auralite/ui/switch_control.h"
#include "auralite/ui/text_area.h"
#include "auralite/ui/text_field.h"
#include "auralite/ui/text_layout.h"
#include "auralite/ui/title_bar.h"
#include "auralite/ui/toast.h"
#include "auralite/ui/tree_view.h"
#include "auralite/ui/user_control.h"
#include "auralite/ui/virtual_list.h"

#include "auralite/ui/bind.h"
#include "auralite/ui/dsl.h"
#include "auralite/ui/factory.h"
#include "auralite/ui/yaml_loader.h"

#include "auralite/reactive/observe.h"
#include "auralite/reactive/signal.h"

#include "auralite/async/awaiters.h"
