# Auto-generated from vcxproj. Regenerate: python scripts/gen_cmake_sources.py
set(AURALITE_BASE_SOURCES
  ${AURALITE_ROOT}/base/at_exit.cpp
  ${AURALITE_ROOT}/base/base_switches.cpp
  ${AURALITE_ROOT}/base/command_line.cpp
  ${AURALITE_ROOT}/base/cpu.cpp
  ${AURALITE_ROOT}/base/data_pack.cpp
  ${AURALITE_ROOT}/base/debug_util.cpp
  ${AURALITE_ROOT}/base/environment.cpp
  ${AURALITE_ROOT}/base/file_path.cpp
  ${AURALITE_ROOT}/base/file_util.cpp
  ${AURALITE_ROOT}/base/file_version_info.cpp
  ${AURALITE_ROOT}/base/lazy_instance.cpp
  ${AURALITE_ROOT}/base/lock.cpp
  ${AURALITE_ROOT}/base/lock_impl.cpp
  ${AURALITE_ROOT}/base/logging.cpp
  ${AURALITE_ROOT}/base/native_library.cpp
  ${AURALITE_ROOT}/base/non_thread_safe.cpp
  ${AURALITE_ROOT}/base/path_service.cpp
  ${AURALITE_ROOT}/base/pickle.cpp
  ${AURALITE_ROOT}/base/platform_file.cpp
  ${AURALITE_ROOT}/base/rand_util.cpp
  ${AURALITE_ROOT}/base/ref_counted.cpp
  ${AURALITE_ROOT}/base/ref_counted_memory.cpp
  ${AURALITE_ROOT}/base/registry.cpp
  ${AURALITE_ROOT}/base/resource_util.cpp
  ${AURALITE_ROOT}/base/rtl.cpp
  ${AURALITE_ROOT}/base/scoped_variant.cpp
  ${AURALITE_ROOT}/base/string_number_conversions.cpp
  ${AURALITE_ROOT}/base/string_piece.cpp
  ${AURALITE_ROOT}/base/string_split.cpp
  ${AURALITE_ROOT}/base/string_util.cpp
  ${AURALITE_ROOT}/base/stringprintf.cpp
  ${AURALITE_ROOT}/base/sys_info.cpp
  ${AURALITE_ROOT}/base/sys_string_conversions.cpp
  ${AURALITE_ROOT}/base/thread_checker.cpp
  ${AURALITE_ROOT}/base/thread_local.cpp
  ${AURALITE_ROOT}/base/thread_local_storage.cpp
  ${AURALITE_ROOT}/base/time.cpp
  ${AURALITE_ROOT}/base/utf_string_conversion_utils.cpp
  ${AURALITE_ROOT}/base/utf_string_conversions.cpp
  ${AURALITE_ROOT}/base/values.cpp
  ${AURALITE_ROOT}/base/version.cpp
  ${AURALITE_ROOT}/base/vlog.cpp
  ${AURALITE_ROOT}/base/waitable_event.cpp
  ${AURALITE_ROOT}/base/weak_ptr.cpp
  ${AURALITE_ROOT}/base/win_util.cpp
  ${AURALITE_ROOT}/base/windows_version.cpp
  ${AURALITE_ROOT}/message_framework/message_loop.cpp
  ${AURALITE_ROOT}/message_framework/message_loop_proxy.cpp
  ${AURALITE_ROOT}/message_framework/message_loop_proxy_impl.cpp
  ${AURALITE_ROOT}/message_framework/message_pump.cpp
  ${AURALITE_ROOT}/message_framework/message_pump_default.cpp
  ${AURALITE_ROOT}/message_framework/message_pump_win.cpp
  ${AURALITE_ROOT}/message_framework/task.cpp
  ${AURALITE_ROOT}/message_framework/task_queue.cpp
  ${AURALITE_ROOT}/message_framework/thread.cpp
  ${AURALITE_ROOT}/message_framework/timer.cpp
  ${AURALITE_ROOT}/rfc_algorithm/base64/base64.cpp
  ${AURALITE_ROOT}/rfc_algorithm/json/json_reader.cpp
  ${AURALITE_ROOT}/rfc_algorithm/json/json_writer.cpp
  ${AURALITE_ROOT}/rfc_algorithm/json/string_escape.cpp
  ${AURALITE_ROOT}/rfc_algorithm/md5/md5.cpp
  ${AURALITE_ROOT}/rfc_algorithm/sha1/sha1.cpp
  ${AURALITE_ROOT}/rfc_algorithm/sha2/sha2.cpp
  ${AURALITE_ROOT}/rfc_algorithm/zlib/adler32.c
  ${AURALITE_ROOT}/rfc_algorithm/zlib/compress.c
  ${AURALITE_ROOT}/rfc_algorithm/zlib/crc32.c
  ${AURALITE_ROOT}/rfc_algorithm/zlib/deflate.c
  ${AURALITE_ROOT}/rfc_algorithm/zlib/gzio.c
  ${AURALITE_ROOT}/rfc_algorithm/zlib/infback.c
  ${AURALITE_ROOT}/rfc_algorithm/zlib/inffast.c
  ${AURALITE_ROOT}/rfc_algorithm/zlib/inflate.c
  ${AURALITE_ROOT}/rfc_algorithm/zlib/inftrees.c
  ${AURALITE_ROOT}/rfc_algorithm/zlib/trees.c
  ${AURALITE_ROOT}/rfc_algorithm/zlib/uncompr.c
  ${AURALITE_ROOT}/rfc_algorithm/zlib/zutil.c
  ${AURALITE_ROOT}/third_party/icu/icu_utf.cc
  ${AURALITE_ROOT}/third_party/modp_b64/modp_b64.cc
  ${AURALITE_ROOT}/third_party/nspr/prtime.cc
  ${AURALITE_ROOT}/third_party/nss/sha512.cc
)

set(AURALITE_UI_SOURCES
  ${AURALITE_ROOT}/animation/animation.cpp
  ${AURALITE_ROOT}/animation/animation_container.cpp
  ${AURALITE_ROOT}/animation/linear_animation.cpp
  ${AURALITE_ROOT}/animation/multi_animation.cpp
  ${AURALITE_ROOT}/animation/slide_animation.cpp
  ${AURALITE_ROOT}/animation/throb_animation.cpp
  ${AURALITE_ROOT}/animation/tween.cpp
  ${AURALITE_ROOT}/gfx/bitmap.cpp
  ${AURALITE_ROOT}/gfx/bitmap_operations.cpp
  ${AURALITE_ROOT}/gfx/canvas_d2d.cpp
  ${AURALITE_ROOT}/gfx/dwrite_text.cpp
  ${AURALITE_ROOT}/gfx/color_utils.cpp
  ${AURALITE_ROOT}/gfx/font.cpp
  ${AURALITE_ROOT}/gfx/gdi_util.cpp
  ${AURALITE_ROOT}/gfx/insets.cpp
  ${AURALITE_ROOT}/gfx/native_theme_win.cpp
  ${AURALITE_ROOT}/gfx/path.cpp
  ${AURALITE_ROOT}/gfx/platform_bitmap_win.cpp
  ${AURALITE_ROOT}/gfx/platform_font_win.cpp
  ${AURALITE_ROOT}/gfx/point.cpp
  ${AURALITE_ROOT}/gfx/rect.cpp
  ${AURALITE_ROOT}/gfx/size.cpp
  ${AURALITE_ROOT}/gfx/window_impl.cpp
  ${AURALITE_ROOT}/view_framework/accessibility/view_accessibility_msaa.cpp
  ${AURALITE_ROOT}/view_framework/accessibility/view_accessibility_wrapper.cpp
  ${AURALITE_ROOT}/view_framework/animation/bounds_animator.cpp
  ${AURALITE_ROOT}/view_framework/app/dwmapi_wrapper.cpp
  ${AURALITE_ROOT}/view_framework/app/event.cpp
  ${AURALITE_ROOT}/view_framework/app/keyboard_code_conversion_win.cpp
  ${AURALITE_ROOT}/view_framework/app/resource_bundle.cpp
  ${AURALITE_ROOT}/view_framework/app/screen.cpp
  ${AURALITE_ROOT}/view_framework/app/system_monitor.cpp
  ${AURALITE_ROOT}/view_framework/app/windows_util.cpp
  ${AURALITE_ROOT}/view_framework/clipboard/clipboard_util_win.cpp
  ${AURALITE_ROOT}/view_framework/controls/button/button.cpp
  ${AURALITE_ROOT}/view_framework/controls/button/custom_button.cpp
  ${AURALITE_ROOT}/view_framework/controls/button/image_button.cpp
  ${AURALITE_ROOT}/view_framework/controls/button/native_button.cpp
  ${AURALITE_ROOT}/view_framework/controls/button/native_button_win.cpp
  ${AURALITE_ROOT}/view_framework/controls/button/text_button.cpp
  ${AURALITE_ROOT}/view_framework/controls/checkbox.cpp
  ${AURALITE_ROOT}/view_framework/controls/image_view.cpp
  ${AURALITE_ROOT}/view_framework/controls/label.cpp
  ${AURALITE_ROOT}/view_framework/controls/list_view.cpp
  ${AURALITE_ROOT}/view_framework/controls/menu/menu_model.cpp
  ${AURALITE_ROOT}/view_framework/controls/menu/menu_runner.cpp
  ${AURALITE_ROOT}/view_framework/controls/menu/simple_menu_model_controller.cpp
  ${AURALITE_ROOT}/view_framework/controls/radio_button.cpp
  ${AURALITE_ROOT}/view_framework/controls/scroll_view.cpp
  ${AURALITE_ROOT}/view_framework/controls/switch.cpp
  ${AURALITE_ROOT}/view_framework/controls/textfield.cpp
  ${AURALITE_ROOT}/view_framework/controls/native_control_win.cpp
  ${AURALITE_ROOT}/view_framework/controls/native_view_host.cpp
  ${AURALITE_ROOT}/view_framework/controls/native_view_host_win.cpp
  ${AURALITE_ROOT}/view_framework/controls/single_split_view.cpp
  ${AURALITE_ROOT}/view_framework/dragdrop/drag_drop_types.cpp
  ${AURALITE_ROOT}/view_framework/dragdrop/drag_source.cpp
  ${AURALITE_ROOT}/view_framework/dragdrop/drop_helper.cpp
  ${AURALITE_ROOT}/view_framework/dragdrop/drop_target.cpp
  ${AURALITE_ROOT}/view_framework/dragdrop/drop_target_win.cpp
  ${AURALITE_ROOT}/view_framework/dragdrop/os_exchange_data.cpp
  ${AURALITE_ROOT}/view_framework/dragdrop/os_exchange_data_provider_win.cpp
  ${AURALITE_ROOT}/view_framework/focus/accelerator_handler.cpp
  ${AURALITE_ROOT}/view_framework/focus/focus_manager.cpp
  ${AURALITE_ROOT}/view_framework/focus/focus_search.cpp
  ${AURALITE_ROOT}/view_framework/focus/focus_util_win.cpp
  ${AURALITE_ROOT}/view_framework/focus/view_storage.cpp
  ${AURALITE_ROOT}/view_framework/gfx/background.cpp
  ${AURALITE_ROOT}/view_framework/gfx/border.cpp
  ${AURALITE_ROOT}/view_framework/gfx/default_theme_provider.cpp
  ${AURALITE_ROOT}/view_framework/gfx/painter.cpp
  ${AURALITE_ROOT}/view_framework/gfx/theme_provider.cpp
  ${AURALITE_ROOT}/view_framework/layout/box_layout.cpp
  ${AURALITE_ROOT}/view_framework/layout/fill_layout.cpp
  ${AURALITE_ROOT}/view_framework/layout/grid_layout.cpp
  ${AURALITE_ROOT}/view_framework/layout/layout_manager.cpp
  ${AURALITE_ROOT}/view_framework/view.cpp
  ${AURALITE_ROOT}/view_framework/widget/aero_tooltip_manager.cpp
  ${AURALITE_ROOT}/view_framework/widget/root_view.cpp
  ${AURALITE_ROOT}/view_framework/widget/tooltip_manager.cpp
  ${AURALITE_ROOT}/view_framework/widget/tooltip_manager_win.cpp
  ${AURALITE_ROOT}/view_framework/widget/widget_win.cpp
  ${AURALITE_ROOT}/view_framework/window/client_view.cpp
  ${AURALITE_ROOT}/view_framework/window/custom_frame_view.cpp
  ${AURALITE_ROOT}/view_framework/window/dialog_client_view.cpp
  ${AURALITE_ROOT}/view_framework/window/dialog_delegate.cpp
  ${AURALITE_ROOT}/view_framework/window/native_frame_view.cpp
  ${AURALITE_ROOT}/view_framework/window/non_client_view.cpp
  ${AURALITE_ROOT}/view_framework/window/window.cpp
  ${AURALITE_ROOT}/view_framework/window/window_delegate.cpp
  ${AURALITE_ROOT}/view_framework/window/window_win.cpp
)
