# Auto-generated from vcxproj. Regenerate: python scripts/gen_cmake_sources.py
set(MXUI_BASE_SOURCES
  ${MXUI_ROOT}/base/at_exit.cpp
  ${MXUI_ROOT}/base/base_switches.cpp
  ${MXUI_ROOT}/base/command_line.cpp
  ${MXUI_ROOT}/base/cpu.cpp
  ${MXUI_ROOT}/base/data_pack.cpp
  ${MXUI_ROOT}/base/debug_util.cpp
  ${MXUI_ROOT}/base/environment.cpp
  ${MXUI_ROOT}/base/file_path.cpp
  ${MXUI_ROOT}/base/file_util.cpp
  ${MXUI_ROOT}/base/file_version_info.cpp
  ${MXUI_ROOT}/base/lazy_instance.cpp
  ${MXUI_ROOT}/base/lock.cpp
  ${MXUI_ROOT}/base/lock_impl.cpp
  ${MXUI_ROOT}/base/logging.cpp
  ${MXUI_ROOT}/base/native_library.cpp
  ${MXUI_ROOT}/base/non_thread_safe.cpp
  ${MXUI_ROOT}/base/path_service.cpp
  ${MXUI_ROOT}/base/pickle.cpp
  ${MXUI_ROOT}/base/platform_file.cpp
  ${MXUI_ROOT}/base/rand_util.cpp
  ${MXUI_ROOT}/base/ref_counted.cpp
  ${MXUI_ROOT}/base/ref_counted_memory.cpp
  ${MXUI_ROOT}/base/registry.cpp
  ${MXUI_ROOT}/base/resource_util.cpp
  ${MXUI_ROOT}/base/rtl.cpp
  ${MXUI_ROOT}/base/scoped_variant.cpp
  ${MXUI_ROOT}/base/string_number_conversions.cpp
  ${MXUI_ROOT}/base/string_piece.cpp
  ${MXUI_ROOT}/base/string_split.cpp
  ${MXUI_ROOT}/base/string_util.cpp
  ${MXUI_ROOT}/base/stringprintf.cpp
  ${MXUI_ROOT}/base/sys_info.cpp
  ${MXUI_ROOT}/base/sys_string_conversions.cpp
  ${MXUI_ROOT}/base/thread_checker.cpp
  ${MXUI_ROOT}/base/thread_local.cpp
  ${MXUI_ROOT}/base/thread_local_storage.cpp
  ${MXUI_ROOT}/base/time.cpp
  ${MXUI_ROOT}/base/utf_string_conversion_utils.cpp
  ${MXUI_ROOT}/base/utf_string_conversions.cpp
  ${MXUI_ROOT}/base/values.cpp
  ${MXUI_ROOT}/base/version.cpp
  ${MXUI_ROOT}/base/vlog.cpp
  ${MXUI_ROOT}/base/waitable_event.cpp
  ${MXUI_ROOT}/base/weak_ptr.cpp
  ${MXUI_ROOT}/base/win_util.cpp
  ${MXUI_ROOT}/base/windows_version.cpp
  ${MXUI_ROOT}/message_framework/message_loop.cpp
  ${MXUI_ROOT}/message_framework/message_loop_proxy.cpp
  ${MXUI_ROOT}/message_framework/message_loop_proxy_impl.cpp
  ${MXUI_ROOT}/message_framework/message_pump.cpp
  ${MXUI_ROOT}/message_framework/message_pump_default.cpp
  ${MXUI_ROOT}/message_framework/message_pump_win.cpp
  ${MXUI_ROOT}/message_framework/task.cpp
  ${MXUI_ROOT}/message_framework/task_queue.cpp
  ${MXUI_ROOT}/message_framework/thread.cpp
  ${MXUI_ROOT}/message_framework/timer.cpp
  ${MXUI_ROOT}/rfc_algorithm/base64/base64.cpp
  ${MXUI_ROOT}/rfc_algorithm/json/json_reader.cpp
  ${MXUI_ROOT}/rfc_algorithm/json/json_writer.cpp
  ${MXUI_ROOT}/rfc_algorithm/json/string_escape.cpp
  ${MXUI_ROOT}/rfc_algorithm/md5/md5.cpp
  ${MXUI_ROOT}/rfc_algorithm/sha1/sha1.cpp
  ${MXUI_ROOT}/rfc_algorithm/sha2/sha2.cpp
  ${MXUI_ROOT}/rfc_algorithm/zlib/adler32.c
  ${MXUI_ROOT}/rfc_algorithm/zlib/compress.c
  ${MXUI_ROOT}/rfc_algorithm/zlib/crc32.c
  ${MXUI_ROOT}/rfc_algorithm/zlib/deflate.c
  ${MXUI_ROOT}/rfc_algorithm/zlib/gzio.c
  ${MXUI_ROOT}/rfc_algorithm/zlib/infback.c
  ${MXUI_ROOT}/rfc_algorithm/zlib/inffast.c
  ${MXUI_ROOT}/rfc_algorithm/zlib/inflate.c
  ${MXUI_ROOT}/rfc_algorithm/zlib/inftrees.c
  ${MXUI_ROOT}/rfc_algorithm/zlib/trees.c
  ${MXUI_ROOT}/rfc_algorithm/zlib/uncompr.c
  ${MXUI_ROOT}/rfc_algorithm/zlib/zutil.c
  ${MXUI_ROOT}/third_party/icu/icu_utf.cc
  ${MXUI_ROOT}/third_party/modp_b64/modp_b64.cc
  ${MXUI_ROOT}/third_party/nspr/prtime.cc
  ${MXUI_ROOT}/third_party/nss/sha512.cc
)
